
-- CUSTOMER BEHAVIOR QUERIES:

SELECT * FROM customer_behavior

-- Q1. Total Sales, Total Customers, Average Order Value, Average Review Rating:
SELECT 
SUM(purchase_amount) AS total_sales,
count(DISTINCT customer_id) AS total_customers,
ROUND(SUM(purchase_amount)/COUNT(purchase_amount)::NUMERIC,1) AS aov,
ROUND(AVG(review_rating)::NUMERIC,1) AS avg_review_rating
FROM customer_behavior;

-- Q2. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY gender;

-- Q3. Which customers used a discount but still spent more than the average purchase amount?
SELECT * FROM customer_behavior
WHERE purchase_amount >(SELECT ROUND(AVG(purchase_amount)) AS avg_pur_amount 
FROM customer_behavior) AND discount_applied = 'Yes'

-- Q4. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),2) AS avg_rating FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q5. Compare the average Purchase Amounts between Standard and Express Shipping Type.
SELECT shipping_type, ROUND(AVG(purchase_amount)) AS avg_pur_amount FROM customer_behavior
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q6. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount)) AS avg_spend, SUM(purchase_amount) AS total_revenue 
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q7. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q8. Segment customers into New, Returning, and Loyal based on their total number of previous purcheses, and show the count 
-- of each segment.
WITH customer_type AS (
SELECT *, CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'LOYAL'
		END AS customer_segment
FROM customer_behavior
)
SELECT customer_segment, COUNT(*) FROM customer_type
GROUP BY customer_segment;

-- Q9. What are the top 3 most purchased products within each category?
SELECT * FROM (SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS product_rank 
FROM customer_behavior
GROUP BY category, item_purchased)
WHERE product_rank <= 3;

-- Q10. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(*) AS repeat_buyers FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

-- Q11. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group 
ORDER BY total_revenue DESC

-- Q12. Which 10 location generate the most revenue?
SELECT location, SUM(purchase_amount) AS total_revenue 
FROM customer_behavior
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;

-- Q13. Top 5 customers by spending.
SELECT customer_id, SUM(purchase_amount) AS total_spent
FROM customer_behavior
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 5;

-- Q14. Do discounts increase spending?
SELECT discount_applied, COUNT(*) AS total_orders,
ROUND(AVG(purchase_amount)) AS avg_spending 
FROM customer_behavior
GROUP BY discount_applied
ORDER BY avg_spending DESC;

-- Q15. Which seasons generate the highest sales?
SELECT season, SUM(purchase_amount) AS total_sales
FROM customer_behavior
GROUP BY season
ORDER BY total_sales DESC;

-- Q16. Most used payment methods.
SELECT payment_method, COUNT(*) AS num_transection
FROM customer_behavior
GROUP BY payment_method
ORDER BY num_transection DESC;